- name: Create filter.yaml from template
  template:
    src: filter.tpl
    dest: ./build/filter.yaml
    variable_start_string: '[['
    variable_end_string: ']]'
  vars:
    namespace: "[[ org.name | lower ]]-subs"
    jwksUri: "[[ org.auth.jwksUri ]]"
    audience: "[[ org.auth.audience ]]"
    
- name: Enable JWT Filter for Ambassador
  k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    src: ./build/filter.yaml
