apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oemt-genesis-job
  namespace: oemt-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: oemt-genesis-job
  chart:
    git: https://github.com/inteli-poc/bevel.git
    ref: test-network-dev
    path: platforms/substrate/charts/substrate-genesis
  values:
    node:
      name: oemt-genesis-job
      image: ghcr.io/digicatapult/dscp-node
      imageTag: v4.2.1
      pullPolicy: IfNotPresent
      command: ./dscp-node
    metadata:
      name: oemt-genesis-job
      namespace: oemt-subs
    vault:
      address: http://vault.internal.dev.intelipoc.com:20002
      role: vault-role
      authpath: substrateoemt
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/oemt-subs
    chain: inteli-gcp
    aura_keys: ['5Dst43oYeDPnxf6v544GAvv1iKDzQ8pnwmTfUy7KpAmA2Hbk', '5C5d6pnctvH4ozipL5AbRXB5Ggwp9NKYk6PPDQf3zH5AkUN6']
    grandpa_keys: ['5E3kPxxEQwRvps8ncuCsHxBkcRN4E73dRjdbqiJhNeDSa53G', '5ErhG6d6DJtyYFjXVG96gFpcb8YH8xwxo5YLzW5ZBhU8ELp7']
    members: 
      -   account_id: 5EZRSW6NbmhqnTXyMeAaTqKoGnMXonjfWU8u6fLo9D2JmW8w
          balance: 1152921504606846976
          nodes:
          - 00240801122006FD7F80DAB9253FBD44DB7C51C490350746CCC3ECE9146864F10712A52F7E3A
          - 002408011220746F3F7F70167CC6E41C6E19D5D6582BA688C00150820882E9F17925D25AFAEE
          - 002408011220F9BCF75DE3405CF3837504EFF051C85F213EFC7FBD705F0760D9E0223CB4BD97
          - 0024080112203D5D503286C22E8E833F0E5AAC081A4C82F77015916D23D738C816B078F9430F
      -   account_id: 5GpDnUCcQUoV9absPM9DqdLJQcghjkVqCAWQJGHXjNh97ZxK
          balance: 1152921504606846976
          nodes:
          - 002408011220F55F350B311DF91E4AD8D715CDAE7C10A85C9CEBEB76955EA071361E804F9B77
          - 0024080112201A396174C7DF1D5D4196BBC445E46ACB41AD53F374594827244059CA3E946F62
