{{- if .Values.ingress.enabled -}}
  {{- $fullname :=  include "substrate_chart.name" . -}}
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else if semverCompare ">=1.14-0 <1.19.0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
  {{- include "substrate_node.selectorLabels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- with .Values.ingress.rules }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
  tls:
  {{- with .Values.ingress.tls }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
