apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tiertwo-chain-watcher
  namespace: tiertwo-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: examples/dscp-app/charts/dscp-chain-watcher
  releaseName: tiertwo-chain-watcher
  values:
    fullnameOverride: tiertwo-chain-watcher
    config:
      dbHost: tiertwo-postgresql.tiertwo-subs
      dbPort: 5432
      dbUsername: postgres
      dbPassword: postgres123
      dbName: inteli-api
      dscpApiHost: tiertwo-api.tiertwo-subs
      dscpApiPort: 80
      idServiceHost: tiertwo-id-service.tiertwo-subs
      idServicePort: 3001
    image:
      repository: ghcr.io/inteli-poc/dscp-chain-watcher # {"$imagepolicy": "flux-dev:dscp-chain-watcher:name"}
      pullPolicy: IfNotPresent
      tag: 'v1.1.0-1ee9ae1' # {"$imagepolicy": "flux-dev:dscp-chain-watcher:tag"}
      pullSecrets:
