apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tiertwo-api
  namespace: tiertwo-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/dscp-app/charts/dscp-api
    git: "https://github.com/inteli-poc/bevel.git"
    ref: "vitalam"
  releaseName: tiertwo-api
  values:
    fullNameOverride: tiertwo-api
    config:
      port: 80
      externalNodeHost: "tiertwo"
      externalNodePort: 9944
      logLevel: info  
      externalIpfsHost: "tiertwo-ipfs-api" 
      externalIpfsPort: 5001 
      enableLivenessProbe: true
      substrateStatusPollPeriodMs: 10000
      substrateStatusTimeoutMs: 2000
      ipfsStatusPollPeriodMs: 10000
      ipfsStatusTimeoutMs: 2000
      auth:
        jwksUri: https://inteli-poc.eu.auth0.com/.well-known/jwks.json
        audience: https://inteli-poc.com/api
        issuer: https://inteli-poc.eu.auth0.com/
        tokenUrl: https://inteli-poc.eu.auth0.com/oauth/token
    ingress:
      enabled: false
      className: "gce"
      paths:
        - /v3
    replicaCount: 1
    image:
      repository: ghcr.io/digicatapult/dscp-api
      pullPolicy: IfNotPresent
      tag: 'v4.1.0'
    dscpNode:
      enabled: false

    dscpIpfs:
      enabled: false
      dscpNode:
        enabled: false
    vault:
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      address: http://vault.internal.dev.intelipoc.com:20002
      secretprefix: secretsv2/data/tiertwo-subs/tiertwo
      serviceaccountname: vault-auth
      role: vault-role
      authpath: substratetiertwo

    proxy:
      provider: ambassador
      name: tiertwo 
      external_url_suffix: vitalam.intelipoc.com
      port: 443
      issuedFor: tiertwo
