apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tiertwo-ipfs-node
  namespace: tiertwo-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: tiertwo-ipfs-node
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dscpdev-1
        namespace: flux-dscpdev-1
      chart: platforms/substrate/charts/dscp-ipfs-node
  values:
    fullnameOverride: tiertwo-ipfs
    namespace: tiertwo-subs
    config:
      healthCheckPort: 80
      healthCheckPollPeriod: 30000
      healthCheckTimeout: 2000
      nodeHost: "tiertwo"
      nodePort: "9944"
      logLevel: info
      ipfsApiPort: 5001
      ipfsSwarmPort: 4001
      ipfsDataPath: "/ipfs"
      ipfsCommand: "/usr/local/bin/ipfs"
      ipfsArgs:
        - daemon
        - "--migrate"
      ipfsSwarmAddrFilters: null
      ipfsLogLevel: info
      ipfsBootNodeAddress: /dns4/oem-ipfs-bn-ipfs-swarm.oem-subs.svc.cluster.local/tcp/4001/p2p/12D3KooWRkyxrjKHMYjY3nLUAgR8MFv7bpwkjahcHFTVsJPtBnjE
      
    service:
      swarm:
        annotations: {}
        enabled: true
        port: 4001
      api:
        annotations: {}
        enabled: true
        port: 5001

    statefulSet:
      annotations: {}
      livenessProbe:
        enabled: true
    image:
      repository: ghcr.io/inteli-poc/dscp-ipfs
      pullPolicy: IfNotPresent
      tag: 'v2.6.2'
    storage:
      storageClass: "tiertwo-bevel-storageclass"
      dataVolumeSize: 20  # in Gigabytes
    dscpNode:
      enabled: false
    proxy:
      provider: ambassador
      external_url: tiertwo-ipfs-swarm.sub.blockchaincloudpoc-develop.com
      port: 15031
      certSecret: tiertwo-ambassador-certs
    vault:
      address: http://108.142.38.154:20001
      role: vault-role
      authpath: dscpdev-1tiertwo
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/data/tiertwo/tiertwo
