apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tiertwo-chain-watcher
  namespace: tiertwo-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: examples/dscp-app/charts/dscp-chain-watcher
  releaseName: tiertwo-chain-watcher
  values:
    fullnameOverride: tiertwo-chain-watcher
    metadata:
      namespace: tiertwo-subs
    config:
      dbHost: tiertwo-postgresql.tiertwo-subs
      dbPort: 5432
      dbUsername: postgres
      dbPassword: postgres123
      dbName: inteli-api
      dscpApiHost: tiertwo-api.tiertwo-subs
      dscpApiPort: 80
      idServiceHost: tiertwo-id-service.tiertwo-subs
      idServicePort: 3001
      inteliApiHost: tiertwo-inteli-api.tiertwo-subs
      inteliApiPort: 3000
      inteliApiAudience: https://inteli-poc-tiertwo.com/api
      inteliApiGrant: client_credentials
      inteliApiTokenAddr: https://inteli-poc.eu.auth0.com/oauth/token
      fetchGcpKey: false
    image:
      repository: ghcr.io/inteli-poc/dscp-chain-watcher # {"$imagepolicy": "flux-dev:dscp-chain-watcher:name"}
      pullPolicy: IfNotPresent
      tag: 'v1.31.0-7bcd5e2-1684501857' # {"$imagepolicy": "flux-dev:dscp-chain-watcher:tag"}
      pullSecrets:
    vault:
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      address: http://vault.internal.dev.intelipoc.com:20002
      secretprefix: secretsv2/data/tiertwo-subs
      serviceaccountname: vault-auth
      role: vault-role
      authpath: substratetiertwo
