---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tiertwo-chain-watcher
  namespace: tiertwo-subs
  annotations:
    fluxcd.io/automated: "true"
    repository.fluxcd.io/app: image.repository
    tag.fluxcd.io/app: image.tag
    filter.fluxcd.io/app: 'glob:v1.0.*'
spec:
  chart:
    path: examples/dscp-app/charts/dscp-chain-watcher
    git: "https://github.com/inteli-poc/bevel.git"
    ref: "uat-network"
  releaseName: tiertwo-chain-watcher
  values:
    fullnameOverride: tiertwo-chain-watcher
    config:
      dbHost: tiertwo-postgresql.tiertwo-subs
      dbPort: 5432
      dbUsername: postgres
      dbPassword: postgres123
      dbName: inteli-api
      dscpApiHost: tiertwo-api.tiertwo-subs
      dscpApiPort: 80

    image:
      repository: ghcr.io/inteli-poc/dscp-chain-watcher
      pullPolicy: IfNotPresent
      tag: 'v1.0.04e77a5'
      pullSecrets:
