##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################
#                   Basic Configuration                     #
#############################################################
# Default values for substrate-key-mgmt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  #Provide the namespace for organization's peer
  #Eg. namespace: carrier-subs
  namespace:

  #Provide the name for substrate-key-mgmt job release
  #Eg. name: carrier-keys-job
  name:

node:
  # Provide the name of the peer
  # Eg. name: carrier
  name:
  # Pull substrate Docker image
  image:
  # Pull policy to be used for the Docker image
  # Eg. pullPolicy: IfNotPresent
  pullPolicy: IfNotPresent
  # Command to be invoked to perform operations on the node
  # Eg. command: substrate
  command: 

#############################################################
#               HashiCorp Vault Configuration               #
#############################################################
# NOTE: Make sure that the vault is already unsealed, intialized and configured to 
# use Kubernetes service account token based authentication. 
# For more info, see https://www.vaultproject.io/docs/auth/kubernetes

vault:
  # Provide the vault address
  # Eg. address: http://vault.example.com:8200
  address: 
  # Provide the vault role used.
  # Eg. role: vault-role
  role:
  # Provide the authpath configured to be used.
  authpath:
  # Provide the service account name autheticated to vault.
  # NOTE: Make sure that the service account is already created and autheticated to use the vault.
  # Eg. serviceaccountname: vault-auth
  serviceAccountName:
  # Provide the vault path where the certificates are stored
  # Eg. certsecretprefix: secret/cenm-org-name
  certSecretPrefix:
  
aura_keys:
  # Provide the aura keys in a list format
  # e.g.
  # -5FPQ5bk3kiwpIEH72sayKBJe7Q57xNwAwmes3FA2YW37AE41
  # -5FPQ5bk3i1wadHJWEHUAIBJe7Q57xNwAwmes3FA2YW37AE41
grandpa_keys:
  # Provide the grandpa keys in a list format
  # e.g.
  # -5FPQ5bk3kiwpIEH72sayKBJe7Q57xNwAwmes3FA2YW37AE41
  # -5FPQ5bk3i1wadHJWEHUAIBJe7Q57xNwAwmes3FA2YW37AE41
sudo_key:
  # Provide the key of the dedicated sudo peer
  # e.g.
  # -5FPQ5bk3kiwpIEH72sayKBJe7Q57xNwAwmes3FA2YW37AE41
