apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oem-postgresql
  namespace: oem-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/dscp-app/charts/postgresql
    git: "https://github.com/inteli-poc/bevel.git"
    ref: "uat-network"
  releaseName: oem-postgresql
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 14.4.0
      pullPolicy: IfNotPresent
      debug: false
    global:
      postgresql:
        auth:
          postgresPassword: postgres123
          database: id-service
        service:
          ports:
            postgresql: 5432
    primary:
      initdb:
        scripts:
          create_second_db.sql: |
            CREATE DATABASE "inteli-api";
            GRANT ALL PRIVILEGES ON DATABASE "inteli-api" TO postgres;
        user: postgres
        password: postgres123
