apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oem-ipfs-node
  namespace: oem-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: oem-ipfs-node
  chart:
    git: https://github.com/inteli-poc/bevel.git
    ref: uat-network
    path: platforms/substrate/charts/dscp-ipfs-node
  values:
    fullnameOverride: oem-ipfs
    config:
      healthCheckPort: 80
      healthCheckPollPeriod: 30000
      healthCheckTimeout: 2000
      nodeHost: "oem"
      nodePort: "9944"
      logLevel: info
      ipfsApiPort: 5001
      ipfsSwarmPort: 4001
      ipfsDataPath: "/ipfs"
      ipfsCommand: "/usr/local/bin/ipfs"
      ipfsArgs:
        - daemon
        - "--migrate"
      ipfsSwarmAddrFilters: null
      ipfsLogLevel: info
      ipfsBootNodeAddress: /dns4/oem-ipfs-bn-ipfs-swarm.oem-subs.svc.cluster.local/tcp/4001/p2p/12D3KooWE5f3AAeg1ZLn2H2sX7CosntSi7hqK4tiivUjALMtyLsJ
      
    service:
      swarm:
        annotations: {}
        enabled: true
        port: 4001
      api:
        annotations: {}
        enabled: true
        port: 5001

    statefulSet:
      annotations: {}
      livenessProbe:
        enabled: true
    image:
      repository: ghcr.io/digicatapult/dscp-ipfs
      pullPolicy: IfNotPresent
      tag: 'v2.6.1'
    storage:
      storageClass: "gcpstorageclass"
      dataVolumeSize: 20  # in Gigabytes
    dscpNode:
      enabled: false
    proxy:
      provider: ambassador
      external_url: oem-ipfs-swarm.subs.intelipoc.com
      port: 15065
      certSecret: oem-ambassador-certs
    vault:
      address: http://vault.internal.uat.intelipoc.com:20004
      role: vault-role
      authpath: substrateoem
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/data/oem-subs/oem
