apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oem-id-service
  namespace: oem-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/dscp-app/charts/dscp-identity-service
    git: "https://github.com/inteli-poc/bevel.git"
    ref: "vitalam"
  releaseName: oem-id-service
  values:
    fullNameOverride: oem-id-service
    config:
      externalNodeHost: oem
      externalPostgresql: oem-id-service-postgresql.oem-subs
      port: 3001
      logLevel: info
      dbName: inteli
      dbPort: 5432
      enableLivenessProbe: true
      selfAddress: 
      auth:
        type: JWT
        jwksUri: https://inteli-poc.eu.auth0.com/.well-known/jwks.json
        audience: https://inteli-poc.com/api
        issuer: https://inteli-poc.eu.auth0.com/
        tokenUrl: https://inteli-poc.eu.auth0.com/oauth/token
    ingress:
      enabled: false
      # annotations: {}
      # className
      paths:
        - /v1/members
    replicaCount: 1
    image:
      repository: ghcr.io/digicatapult/dscp-identity-service
      pullPolicy: IfNotPresent
      tag: 'v1.6.0'
      pullSecrets: 

    postgresql:
      enabled: false
      postgresqlDatabase: inteli
      postgresqlUsername: postgres
      postgresqlPassword: postgres123
    dscpNode:
      enabled: false

    vault:
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      address: http://vault.internal.dev.intelipoc.com:20002
      secretprefix: secretsv2/data/oem-subs/oem
      serviceaccountname: vault-auth
      role: vault-role
      authpath: substrateoem

    proxy:
      provider: ambassador
      name: oem 
      external_url_suffix: vitalam.intelipoc.com
      port: 443
      issuedFor: oem
