apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oem-genesis-job
  namespace: oem-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: oem-genesis-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dscp
        namespace: flux-dscp
      chart: platforms/substrate/charts/substrate-genesis
  values:
    node:
      name: oem-genesis-job
      image: ghcr.io/inteli-poc/dscp-node
      imageTag: v4.3.1
      pullPolicy: IfNotPresent
      command: ./dscp-node
    metadata:
      name: oem-genesis-job
      namespace: oem-subs
    vault:
      address: http://inteli-vault.dev.intelipoc.com
      role: vault-role
      authpath: dscpoem
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/oem
    chain: inteli
    aura_keys: ['5DRUmQsWeErswJoo3kogpzggX75EQrfytqabBimwnynsXBw6', '5E9QjHMjqEUnGqE2fDC48srnuAybi1FhSjgjDzssVfsg48pL', '5H3RS5U5hyRdVhYs8j4XWoCjUAxTrh7z4b9EusrptKVbXKry', '5CtQoenhTYhVi25t2VY1QkumkyMBShnJhJYgPew8zdVYdQJx']
    grandpa_keys: ['5EnMp57WMGTALtyQwZy4JqD4ZVdMBXfZZzuuwuBbZQqC5U4p', '5GB2hco3PMNF24FFNz7uuNnoGsSpw29KcBiA9w2EdYbcvkyx', '5FYjyYD1QNS5Njr121VLHydSSJh3XdmoAodoURS4UwqB7NVy', '5FteiPGVqY3HcZhVoToLTjNpg5LKDhSqtHpXJsVEKi5j94qn']
    members: 
      -   account_id: 5F1vWyLtaU7kA4KFXb3AWpRFYG55APwWgFpzo7H7wHdJyHVV
          balance: 1152921504606846976
          nodes:
          - ''
          - ''
          - ''
          - ''
          - ''
      -   account_id: 5He135EqCF2bLzCXuKpPbgVM3EauvULRQfMHEJvLinc8TRbB
          balance: 1152921504606846976
          nodes:
          - ''
          - ''
          - ''
      -   account_id: 5CJxBs9jjTUMBWXKXHyNnuVFuEayJqCdC8ht13D2K6ERtTNy
          balance: 1152921504606846976
          nodes:
          - ''
