##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
---
global:
  serviceAccountName: vault-auth
  vault:
    type: "hashicorp"
    network: substrate
    address: "http://inteli-vault.stage.intelipoc.com"
    authPath: oem
    secretEngine: secretsv3 # secretsv2
    certPrefix: "subs"
    secretPrefix: "data/oem"
    role: vault-role
  cluster:
    provider: azure
    cloudNativeServices: false
    kubernetesUrl: https://inteli-stage-dns-2l39y5xx.hcp.eastus.azmk8s.io:443
