##############################################################################################
#  This Chart is a fork from https://github.com/digicatapult/vitalam-ipfs
#  Please update if needed
##############################################################################################
apiVersion: v2
name: vitalam-ipfs-node
appVersion: '1.2.12'
description: A Helm chart for vitalam-ipfs
version: '1.2.12'
type: application
