config:
  port: 80
  dscpApiHost: dscp-api
  dscpApiPort: 80
  logLevel: info
  dbName: inteli
  dbPort: 5432
  identityServiceHost: localhost
  identityServicePort: 80
  auth:
    type: NONE
    jwksUri: https://inteli.eu.auth0.com/.well-known/jwks.json
    audience: inteli-dev
    issuer: https://inteli.eu.auth0.com/
    tokenUrl: https://inteli.eu.auth0.com/oauth/token

ingress:
  # annotations: {}
  # className: ""
  paths:
    - /v1/attachment
    - /v1/build
    - /v1/order
    - /v1/part
    - /v1/recipe

image:
  repository: ghcr.io/digicatapult/inteli-api
  pullPolicy: IfNotPresent
  tag: 'v1.25.10'
  pullSecrets: ['ghcr-digicatapult']

postgresql:
  enabled: true
  postgresqlDatabase: inteli
  postgresqlUsername: postgres
  postgresqlPassword: postgres
