##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Check if the pods for the organizations are up and running
- name: "Waiting for peer pod {{ peer.name }} in {{ component_ns }}"
  include_role:
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ component_ns }}"
    component_name: "{{ peer.name }}"
    kubernetes: "{{ org.k8s }}"
    label_selectors:
      - app.kubernetes.io/name = {{ component_name }}
      - chain = {{ network.config.chain }}
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: (peer.postgresql is defined) and (peer.inteli_api is defined)

# Create postgresql values file for inteli-api
- name: "Creating postgresql values file for inteli-api"
  include_role:
    name: "{{ playbook_dir }}/roles/create/dscp/postgresql"
  vars:
    component_ns: "{{ org.name | lower }}-subs"
    component_gitops: "{{ org.gitops }}"
    attached_to: "inteli-api"
    values_dir: "{{ playbook_dir }}/../../../{{ org.gitops.release_dir }}/{{ org.name | lower }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: (peer.postgresql is defined) and (peer.id_service is defined)

# Create inteli-api values file for the peer nodes
- name: "Create inteli-api values file for all peers"
  include_role:
    name: helm_component
  vars:
    type: "inteli-api"
    component_name: "{{ peer.name }}-inteli-api"
    name: "{{ peer.name }}"
    charts_dir: "examples/dscp-app/charts"
    account_addr: "{{ account_id.stdout }}"
    db_address: "{{ peer.name }}-inteli-api-postgresql"
    dscp_api_addr: "{{ peer.name }}-api"
    id_service_addr: "{{ peer.name }}-id-service"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: (peer.postgresql is defined) and (peer.inteli_api is defined)

# Push the inteli-api deployment files to repository
- name: "Push the created deployment files to repository"
  include_role: 
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ component_gitops }}"
    GIT_RESET_PATH: "platforms/substrate/configuration"
    msg: "[ci skip] Pushing deployment files for inteli-api"

# Wait for inteli-api Pod to run
- name: "Waiting for inteli-api pod in {{ component_ns }}"
  include_role:
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ component_ns }}"
    component_name: "{{ peer.name }}-inteli-api"
    kubernetes: "{{ org.k8s }}"
    label_selectors:
      - name = {{ component_name }}
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: (peer.postgresql is defined) and (peer.inteli_api is defined)
