##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chain-watcher.fullname" . }}-cron-job
  labels:
    app.kubernetes.io/name: {{ include "chain-watcher.fullname" . }}-cron-job
spec:
  schedule: "*/1 22 * * *" #Everyday at 22:01
  jobTemplate:
    spec:
      backoffLimit: 6
      template:
        metadata:
          labels:
            app: {{ include "chain-watcher.fullname" . }}-cron-job
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
          containers:
          - name: {{ include "chain-watcher.fullname" . }}-cron-job
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
            env:
              - name: DB_HOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "chain-watcher.fullname" . }}-config
                    key: dbHost
              - name: DB_PORT
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "chain-watcher.fullname" . }}-config
                    key: dbPort
              - name: DB_NAME
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "chain-watcher.fullname" . }}-config
                    key: dbName
              - name: DSCP_API_HOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "chain-watcher.fullname" . }}-config
                    key: dscpApiHost
              - name: DSCP_API_PORT
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "chain-watcher.fullname" . }}-config
                    key: dscpApiPort
              - name: DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: {{ include "chain-watcher.fullname" . }}-secret
                    key: dbUsername
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ include "chain-watcher.fullname" . }}-secret
                    key: dbPassword
              - name: IDENTITY_SERVICE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "chain-watcher.fullname" . }}-config
                    key: idServiceHost
              - name: IDENTITY_SERVICE_PORT
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "chain-watcher.fullname" . }}-config
                    key: idServicePort
