apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dscp-chain-watcher-auto
  namespace: flux-dev
spec:
  releaseName: dscp-chain-watcher-auto
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/flux-imageautomation
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    image:
      name: dscp-chain-watcher
      repository: ghcr.io/inteli-poc/dscp-chain-watcher
      pullSecrets: regcred
      
      pollingInterval: 1m0s
      policy: ^1.x

    git:
      fluxrepo: flux-dev
      branch: develop
      commitMessage: "Updated image"
