##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

metadata:
  name: 
  #should hold the name of your vitalam-frontend release
  #E.g. name: test
  namespace:
  #should hold the namespace of your vitalam-frontend release
  #E.g. namespace: test-deployment
  labels:
  # prefix for the deployment names e.g orgName (cenm)

config:
  port: 
  #should contain the port number for HTTP protocol
  #E.g. 80
  logLevel: 
  #E.g. loglevel: info
  #Provide the value for tlsstatus to be true or false for organization's peer
  enableLivenessProbe: true

  applicationConfig:
    authDomain: 
    #should contain the domain name of the Auth0 API

    clientID: 
    ##sensitive data to be stored in vault
    #should hold the Client ID provided by Auth0 for the API

    custAuthClientID: 
    ##sensitive data to be stored in vault
    #should hold Client ID provided by Auth0 for identifying the OEM frontend login requests

    t1AuthClientID: 
    ##sensitive data to be stored in vault
    #should hold Client ID provided by Auth0 for identifying the tier 1 supplier frontend login requests

    authAudience: 
    #should hold the identifier of the Auth0 API

    apiHost: 
    #should hold the address on which the API should run on
    #E.g. localhost

    apiPort: 
    #should hold the port that the API should connect to

    substrateHost: 
    #should hold the address that substrate should run on
    #E.g. localhost

    substratePort:
    #should hold port that the substrate network connects to

    vitalamDemoPersona:
    #you can pick a persona from either cust, lab, am, am-lab

ingress:
  # annotations: {}
  # className: ""
  paths:
    - /

image:
  repository: 
  # The image repository that you are pulling the image from
  pullSecret: 
  # The kubernetes secret used to access the image
  tag:
  # The version of your image
  pullPolicy: IfNotPresent
