apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tierone-web
  namespace: tierone-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dscp
        namespace: flux-dscp
      chart: examples/dscp-app/charts/dscp-frontend
  releaseName: tierone-web
  values:
    fullNameOverride: tierone-web
    config:
      port: 4000
      logLevel: info
      enableLivenessProbe: false
      inteliApiAddr: https://tierone-inteli-api.dev.intelipoc.com/v1/
      logo: inteli.svg
      kinaxisUrl: https://na1.kinaxis.net/web/ACCD01_DEM01/
      persona: Supplier
    auth:
      frontendDomain: inteli-poc.eu.auth0.com
      frontendScope: read:messages
      inteliApiAudience: https://inteli-poc-tierone.com/api
    ingress:
      enabled: false
      className: "gce"
      paths:
        - /
    replicaCount: 1
    image:
      repository: ghcr.io/inteli-poc/inteli-frontend  # {"$imagepolicy": "flux-dscp:inteli-frontend:name"}
      pullPolicy: Always
      tag: 'v1.3.1-a9b2b40-1673367333' # {"$imagepolicy": "flux-dscp:inteli-frontend:tag"}
    vault:
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      address: http://inteli-vault.dev.intelipoc.com
      secretprefix: secretsv2/data/tierone
      serviceaccountname: vault-auth
      role: vault-role
      authpath: "dscptierone"
    proxy:
      provider: ambassador
      name: tierone
      external_url_suffix: dev.intelipoc.com
      issuedFor: tierone
