apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tierone-web
  namespace: tierone-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: examples/dscp-app/charts/dscp-frontend    
  releaseName: tierone-web
  values:
    fullNameOverride: tierone-web
    config:
      port: 80      
      logLevel: info      
      enableLivenessProbe: true
      applicationConfig:
        authDomain: inteli-poc.eu.auth0.com
        clientID: PI0zLbksZgYnAVMU1BDKjMQ1CZ86ctio
        authAudience: https://inteli-poc.com/api
        apiScheme: https
        apiHost: tierone-api.vitalam.intelipoc.com
        apiPort: 443
        substrateHost: "tierone"
        substratePort: 9944         
        inteliDemoPersona: am
        inteliCustIdentity: 5FueJvjmuZHV1ac11JDQeXQ1jsnUTUWfCLvcd2Bm45sPcRnW
        inteliAmIdentity: 5HNSVrPMz7aEGF69QoD8aoNCt8KpX8YyXCVeqJtBC5SpJEMj
        inteliLabIdentity: 5H3G5a5xJNg5xgPLLjkRXLBicTjMzkFAtFQcRbUmeaw6Fip3
        inteliAmlabIdentity: 5H3G5a5xJNg5xgPLLjkRXLBicTjMzkFAtFQcRbUmeaw6Fip3
    ingress: 
      enabled: false
      className: "gce"
      paths:
        - /
    replicaCount: 1
    image:
      repository: ghcr.io/inteli-poc/inteli-demo
      pullPolicy: Always
      tag: 'v3.0.1'

    vault:
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      address: http://vault.internal.dev.intelipoc.com:20002
      secretprefix: secretsv2/data/tierone-subs/tierone
      serviceaccountname: vault-auth
      role: vault-role
      authpath: substratetierone

    proxy:
      provider: ambassador
      name: tierone 
      external_url_suffix: vitalam.intelipoc.com      
      issuedFor: tierone
