apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tierone-ipfs-node
  namespace: tierone-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: tierone-ipfs-node
  chart:
    git: https://github.com/inteli-poc/bevel.git
    ref: vitalam
    path: platforms/substrate/charts/dscp-ipfs-node
  values:
    fullnameOverride: tierone-ipfs
    config:
      healthCheckPort: 80
      nodeHost: "tierone"
      nodePort: "9944"
      logLevel: info
      ipfsApiPort: 5001
      ipfsSwarmPort: 4001
      ipfsDataPath: "/ipfs"
      ipfsCommand: "/usr/local/bin/ipfs"
      ipfsArgs:
        - daemon
      ipfsSwarmAddrFilters: null
      ipfsLogLevel: fatal
      ipfsBootNodeAddress: /dns4/oem-ipfs-bn-ipfs-swarm.oem-subs.svc.cluster.local/tcp/4001/p2p/12D3KooWFNX8Hko5iymACknaLQQev4s1puF6TWwNghAZpaJPg1sP
      
      enableLivenessProbe: true
    image:
      repository: ghcr.io/digicatapult/dscp-ipfs
      pullPolicy: IfNotPresent
      tag: 'v2.4.0'
    storage:
      storageClass: "gcpstorageclass"
      dataVolumeSize: 20  # in Gigabytes
    dscpNode:
      enabled: false
    proxy:
      provider: ambassador
      external_url: tierone-ipfs-swarm.vitalam.intelipoc.com
      port: 15021
      certSecret: tierone-ambassador-certs
    vault:
      address: http://vault.internal.dev.intelipoc.com:20002
      role: vault-role
      authpath: substratetierone
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/data/tierone-subs/tierone
