apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tierone-chain-watcher
  namespace: tierone-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: examples/dscp-app/charts/dscp-chain-watcher
  releaseName: tierone-chain-watcher
  values:
    fullnameOverride: tierone-chain-watcher
    config:
      dbHost: tierone-postgresql.tierone-subs
      dbPort: 5432
      dbUsername: postgres
      dbPassword: postgres123
      dbName: inteli-api
      dscpApiHost: tierone-api.tierone-subs
      dscpApiPort: 80
      idServiceHost: tierone-id-service.tierone-subs
      idServicePort: 3001
    image:
      repository: ghcr.io/inteli-poc/dscp-chain-watcher # {"$imagepolicy": "flux-dev:dscp-chain-watcher:name"}
      pullPolicy: IfNotPresent
      tag: 'v1.31.0-75faaf3-1677680083' # {"$imagepolicy": "flux-dev:dscp-chain-watcher:tag"}
      pullSecrets:
    vault:
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      address: http://vault.internal.dev.intelipoc.com:20002
      secretprefix: secretsv2/data/tierone-subs
      serviceaccountname: vault-auth
      role: vault-role
      authpath: substratetierone
      createInitContainer: false
