apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tierone-web
  namespace: tierone-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/dscp-app/charts/dscp-frontend
    git: "https://github.com/inteli-poc/bevel.git"
    ref: "vitalam"
  releaseName: tierone-web
  values:
    fullNameOverride: tierone-web
    config:
      port: 80      
      logLevel: info      
      enableLivenessProbe: true
      applicationConfig:
        authDomain: inteli-poc.eu.auth0.com
        clientID: PI0zLbksZgYnAVMU1BDKjMQ1CZ86ctio
        authAudience: https://inteli-poc.com/api
        apiScheme: https
        apiHost: tierone-api.vitalam.intelipoc.com
        apiPort: 443
        substrateHost: "tierone"
        substratePort: 9944         
        inteliDemoPersona: am
        inteliCustIdentity: 5GnGDH3iZzZ2PRWWUyAU5c9QqUDywmDJcWmuuzVEeCkqkXmH
        inteliAmIdentity: 5CPiTSvEat7zq3TihH49tyoQaQmc92JzRBmfLfSzTXCaXsVS
        inteliLabIdentity: 5G6SxXKNJoSg7Z8kUSuzhwUf18pVMMRceQ2bRooymczf2T2c
        inteliAmlabIdentity: 5G6SxXKNJoSg7Z8kUSuzhwUf18pVMMRceQ2bRooymczf2T2c
    ingress: 
      enabled: false
      className: "gce"
      paths:
        - /
    replicaCount: 1
    image:
      repository: ghcr.io/inteli-poc/inteli-demo
      pullPolicy: Always
      tag: 'v3.0.1'

    vault:
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      address: http://vault.internal.dev.intelipoc.com:20002
      secretprefix: secretsv2/data/tierone-subs/tierone
      serviceaccountname: vault-auth
      role: vault-role
      authpath: substratetierone

    proxy:
      provider: ambassador
      name: tierone 
      external_url_suffix: vitalam.intelipoc.com      
      issuedFor: tierone
