##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

charts:
  dscp-api: dscp-api
  dscp-frontend: dscp-frontend
  certissuer: certissuer
