##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v2
name: dscp-chain-watcher
appVersion: '1.1.8'
description: A Helm chart for dscp-chain-watcher
version: '1.1.8'
type: application
