fullnameOverride:

config:
  dbHost:
  dbPort:
  dbUsername: 
  dbPassword: 
  dbName: 
  dscpApiHost:
  dscpApiPort: 
  idServiceHost:
  idServicePort:

image:
  repository: ghcr.io/inteli-poc/dscp-chain-watcher
  pullPolicy: IfNotPresent
  tag: 'v1.0.2'
  pullSecrets: 
