---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oem-inteliapi-cert
  namespace: oem-subs
spec:
  secretName: oem-inteliapi-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - oem-inteli-api.stage.intelipoc.com

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: acme-oem-inteliapi
  namespace: oem-subs
spec:
  hostname: oem-inteli-api.stage.intelipoc.com # "*"
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  service: acme-oem-inteliapi-svc

---
apiVersion: v1
kind: Service
metadata:
  name: acme-oem-inteliapi-svc
  namespace: oem-subs
spec:
  ports:
  - port: 80
    targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"

---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: oem-inteli-host
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  hostname: oem-inteli-api.stage.intelipoc.com
  requestPolicy:
    insecure:
      action: Route
  tls:
    min_tls_version: v1.2
  tlsSecret:
    name: oem-inteliapi-cert
    namespace: oem-subs

# kubectl apply -f examples/dscp-app/inteli-helm/cert-process/oem-inteli-api.yml
# kubectl delete -f examples/dscp-app/inteli-helm/cert-process/oem-inteli-api.yml
